<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.4.2" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UserSecretsId>2f79ff46-8051-4fd0-a5b7-b9c66b5e7537</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" />
    <PackageReference Include="Aspire.Hosting.NodeJs" />
    <PackageReference Include="Aspire.Hosting.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lms.Api\Lms.Api.csproj" />
    <ProjectReference Include="..\Lms.Migrations\Lms.Migrations.csproj" />
  </ItemGroup>

</Project>
